# Generated by Django 3.2.3 on 2021-07-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalexam',
            old_name='specialist',
            new_name='orientation_specialist',
        ),
        migrations.RenameField(
            model_name='medicalexam',
            old_name='motife',
            new_name='reason',
        ),
    ]
