# Generated by Django 3.2.3 on 2021-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20210714_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexam',
            name='visual_acuity_without_correction_right',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
