# Generated by Django 3.2.3 on 2021-07-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210714_1141'),
        ('medical', '0003_medicalexam_visual_acuity_without_correction_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexam',
            name='patient',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
    ]
