# Generated by Django 3.2.3 on 2021-07-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210714_1141'),
        ('medical', '0005_alter_medicalexam_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
    ]
