# Generated by Django 3.2.3 on 2021-07-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210714_1141'),
        ('medical', '0007_auto_20210714_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient', unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='biometric',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient', unique=True),
        ),
    ]
