# Generated by Django 3.2.3 on 2021-07-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_medicalexam_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='number_units',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
