# Generated by Django 3.2.3 on 2021-06-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ATP', 'ATP'), ('Student', 'Student')], default='Student', max_length=50)),
                ('education_level', models.CharField(choices=[('NONE', 'NONE'), ('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS-ISI', '2CS-ISI'), ('2CS-SIW', '2CS-SIW'), ('3CS-ISI', '3CS-ISI'), ('3CS-SIW', '3CS-SIW')], default='NONE', max_length=50)),
                ('is_approaved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
