# Generated by Django 3.2.3 on 2021-07-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_medicalexam_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='screening',
        ),
        migrations.DeleteModel(
            name='MedicalExam',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
